apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
spec:
  selector:
    matchLabels:
      app: nextjs
  replicas: 2
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs
        image: titanomtechnologies/deutschlandgpt-dialog:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: deutschlandgpt-secret-env
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  selector:
    app: nextjs
  type: NodePort 
  ports:
    - port: 80
      targetPort: 3000
      targetPort: 32001
